<?php

namespace Oppned\Log;

use Oppned\AbstractModel;

/**
 * Class Log
 * @package Oppned\Log
 * @property int $id
 * @property string $user
 * @property string $group
 * @property int $priority
 * @property string $message
 * @property bool $viewed
 */
class Log extends AbstractModel {
	/** @var  int */
	protected $id;
	/** @var  string */
	protected $user;
	/** @var  string  */
	protected $group;
	/** @var  int */
	protected $priority;
	/** @var  string */
	protected $message;
	/** @var  bool */
	protected $viewed;

	public static $priorities = array(
		0 => 'EMERG',
		1 => 'ALERT',
		2 => 'CRIT',
		3 => 'ERR',
		4 => 'WARN',
		5 => 'NOTICE',
		6 => 'INFO',
		7 => 'DEBUG'
	);

	public function exchangeArray($data)
	{
		parent::exchangeArray($data); // TODO: Change the autogenerated stub
		//~r($this);
	}

	public function __set($name, $value) {
		switch($name) {
			case 'priority':
				if(is_numeric($value)) {
					$this->$name = $value;
				}
				else {
					$this->$name = array_search($value, self::$priorities);
				}
				break;
			default:
				parent::__set($name, $value);
				break;
		}
	}
	
	public function __get($name) {
		switch($name) {
			case 'priorityName':
				return self::$priorities[$this-$name];
				break;
			default:
				return parent::__get($name);
				break;
		}
	}

	public function __clone() {
		$this->id = null;
	}

	public function toArray() {
		$data = array();
		foreach ( $this->data as $key => $value ) {
			$data[$key] = $value;
		}
		return $data;
	}

}
